### ISSUE TITLE
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [charliewolf/pynder#101]
```
access_token = 'EAAGm0P...'

Traceback (most recent call last):
  File "tinder.py", line 56, in __init__
    session = pynder.Session(access_token)
  File "/home/me/.local/lib/python3.5/site-packages/pynder-0.0.11-py3.5.egg/pynder/session.py", line 13, in __init__
    self._api.auth(facebook_token)
  File "/home/me/.local/lib/python3.5/site-packages/pynder-0.0.11-py3.5.egg/pynder/api.py", line 24, in auth
    self._url('/auth'), data=data, proxies=self._proxies).json()
  File "/home/me/.local/lib/python3.5/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sfgasdfsafggfgg** [comment]
Closing because the problem has gone after running `pip install --user --upgrade pynder`
