### ISSUE TITLE
Likes not registering

### ISSUE THREAD

**Issue by sof123** [charliewolf/pynder#113]
I noticed that likes using pynder don't seem to be registering. This may be due to the fact that the like and dislike requests that are sent using pynder are different from those sent from a phone. I guess that Tinder has begun to detect third party apps by looking at the request. 

Example LIKE from phone: 
 GET /like/5487586faf967ea817dba49d?photoId=4259df60-51c3-4b06-830a-37a7ac7bd20a&user_traveling=true&content_hash=g2jsrvSzbI8ZUNbcDkTrESdiDYtZuekt6aUd4C9lcObuV&s_number=44784367 HTTP/1.1

Example DISLIKE from phone:
GET /pass/54727412415d94b05fe91462?photoId=469fbb1e-8681-4a01-86f9-4475eb13697e&content_hash=jQAhq5F2AFJsYdtQ0IkdC7IDGs7XI4VikVS4GINSgeT4r&s_number=29415357 HTTP/1.1

Example LIKE from pynder:
GET /like/539d4746689877b66276846f HTTP/1.1

EXAMPLE DISLIKE from pynder:
GET /pass/539d4746689877b66276846f HTTP/1.1

The s_number can be extracted from the list of recommended users returned after doing a GET at /user/recs. 

I'm not sure how to get the content_hash value yet. 

photoId is simply the id of the photo you performed the swipe on. 

user_traveling is whether or not the user is using Tinder Passport.

**Comment by Vinz87** [comment]
For me likes are functioning properly. I retrieve the users who liked me first, and liking them back results in a match.

**Comment by sof123** [comment]
Hmm maybe it's not the request then. But I've noticed that a have a solid match rate when I swipe (about 1 match for every 200 swipes) but have not gotten a single match using an autolike script that I wrote to randomly swipe left/right through users. I've used the script to like at least 5000 people.

**Comment by Vinz87** [comment]
I think I'm experiencing the same issue right now... did you find a workaround?

**Comment by sof123** [comment]
Haven't really tried anything yet since no one seemed to be having the same issue. You said 6 days ago that likes were functioning properly. How long had it been since they actually worked for you when you posted that?

**Comment by Vinz87** [comment]
well I'm still doubtful if they work or not. The point is that I suddenly have a lot of users who appear multiple times when running session.nearby_users(), and previously all of these users would result in a match if I liked them.
Now something changed, and I got like 10 users with repeated appearance which did not result in a match when liking them. So, either likes are not working, or it's not true anymore that repeated user appearance means that they already liked you.

I would say the latter is true, also because if I try to superlike someone, that superlike do counts for the limit of 1 every 24h, if I try another superlike I would receive an error.

**Comment by sof123** [comment]
The "like" from pynder may count against the user's like limit but be quietly ignored on the backend if it does not match the format in the OP. So I'm not sure that that error tells us much but thanks for your input.

**Comment by Vinz87** [comment]
I think the most simple test would be to make two known users to like each other. Unfortunately I don't have a secondary phone number, so I can't register a second Tinder account

**Comment by Vinz87** [comment]
I just discovered that "content_hash" and "s_number" values actually are fields of the /user response.
The like/pass request simply copies the values of those fields.

**Comment by Vinz87** [comment]
try out the modifications I've done and report back if you get some matches ;)

**Comment by sof123** [comment]
Thanks. I'll try it with those modifications later, but I think you should also add the photoId and user_traveling fields to the requests before testing. If you don't want to, I can get around to it next week.

**Comment by halalfood** [comment]
@Vinz87 your pull request failed a check. 

It seems I also seeing way less likes and way more repeats of names as of recently. Either there is a like limit or I've liked everyone in the area. My guess is it has something to do with the requests as well. I could test if you need to once all the checks have passed.

**Comment by Vinz87** [comment]
I can confirm that with these modifications a like of a user who already liked you results in a match.

I don't understand what the failed check is about, I'm not an expert in python. Anyway, the modifications I've done are pretty basic and are visible in the pull request, if someone wants to play around with.

**Comment by pttomcat** [comment]
Hi @Vinz87 

Tried to test your modification.

    return self._session._api.like(self.id)['match']
TypeError: like() takes exactly 4 arguments (2 given)

any thoughts ?

Thanks in advance.

**Comment by VeNoMouS** [comment]
The following wont work..
``` self._session._api.like(self.id)['match']```

The api like() params have changed to..
```
def like(self, user, content_hash, s_number):
```

Try...

``` self._session._api.like(self.id, user.content_hash, user.s_number)['match']```

Assuming user from nearby()... I'm just guessing here..

**Comment by VeNoMouS** [comment]
@sof123 on your original issue, did you notice it liked the user... then the user just disappeared from the constant nearby()?

**Comment by Vinz87** [comment]
@pttomcat I modified the like() function in order to take into account the "content_hash" and "s_number" fields.
therefore you have to save those fields when calling nearby_users()
then you pass them to the like function: like(id, content_hash, s_number)

if you wish, you can also try with my own little project [TndrAssistant](https://github.com/Vinz87/TndrAssistant)

**Comment by pttomcat** [comment]
Oh, that make sense but still got problem:

this is the new code 
    def like(self, user, content_hash, s_number):
     return self._get("/like/{}?content_hash=\"{}\"&s_number=\"{}\"".format(user, content_hash, s_number))
so as long as I pass content_hash  and s_number should work.
  
and this is my code:
session = pynder.Session(FBTOKEN)
users = session.nearby_users()
print users
for user in users[:5]:
    luck = user.like(user.content_hash, user.s_number)

Traceback (most recent call last):
  File "like.py", line 12, in <module>
    luck = user.like(user.content_hash, user.s_number)
TypeError: like() takes exactly 1 argument (3 given)

Not sure what I am doing wrong. probably need to read the code more carefully.

I will have look at TinderAssistant shortly. looks interesting

**Comment by VeNoMouS** [comment]
@pttomcat ```session._api.like()```

**Comment by VeNoMouS** [comment]
@Vinz87 just looking at your code for https://github.com/Vinz87/TndrAssistant , have you considered using  ```cursors.DictCursor``` and named variables ```%(id)s``` , then passing a dict in your sql to minimize security issues such as sql injections... etc?

**Comment by VeNoMouS** [comment]
interim dirty fix... ```if "user" in u and not u["user"]["_id"].startswith("tinder_rate_limited_id_"):```

**Comment by VeNoMouS** [comment]
managed to generate another error in testing..

```
  File "/usr/local/lib/python2.7/dist-packages/pynder-0.0.11-py2.7.egg/pynder/session.py", line 41, in matches
    matches.append(models.Match(m, self))
  File "/usr/local/lib/python2.7/dist-packages/pynder-0.0.11-py2.7.egg/pynder/models/user.py", line 130, in __init__
    self.user = User(user_data, _session)
  File "/usr/local/lib/python2.7/dist-packages/pynder-0.0.11-py2.7.egg/pynder/models/user.py", line 17, in __init__
    setattr(self, f, data[f])
KeyError: 'content_hash'
```

**Comment by sof123** [comment]
@VeNoMouS 

Not sure what you mean. nearby_users() is a method. it's in all likelihood going to get a different list of people every time.

**Comment by sof123** [comment]
@VeNoMouS  I guess I could try in a very sparsely populated area to see if the users are going back into the stack if they've been liked. Is that what you're getting at?

**Comment by VeNoMouS** [comment]
@sof123 unsure if my profile corrupted, but likes weren't registering with people that had liked me, and i stopped getting matches completely.

**Comment by sof123** [comment]
@VeNoMouS That happens sometimes even on the phone app. Use fiddler or something to see the network activity and make sure your likes are going through. I've noticed that several likes are never actually sent to the server for whatever reason.

**Comment by sof123** [comment]
Went ahead and fixed this if anyone still cares. Pull request is failing style tests that I can't be bothered to fix right now but I'm getting matches now and the requests look identical to phone requests. Also, the user_traveling field is defaulted to true and that might be problematic for users who don't have tinder plus. So just change that to "false" instead of "true" on line 123 in user.py if you don't have Tinder Plus. Thanks for everyone's help.

**Comment by sof123** [comment]
Also every 50-100 people or so the content_hash is not found in the GET /user response. I just did a dirty fix and added a try/catch for now in the init method of User in user.py. 

Here's the code: https://github.com/charliewolf/pynder/pull/124

**Comment by sof123** [comment]
After getting 20+ matches yesterday using the autoliker, I try running it again this morning and neither the content_hash nor the s_number is being found on /user requests. Weird.

**Comment by ihavetimetowaste** [comment]
@sof123 Thanks, I also liked > 5000 people without getting a single match... So including these new fields into you like GET requests has fixed your problem? Do you get a different response or still {u'likes_remaining': 100, u'match': False}?

I assume you have just verified this works by actually getting matches now.

**Comment by sof123** [comment]
@ihavetimetowaste

Yes it fixed the problem and yes I'm still getting that response.

**Comment by ttse007** [comment]
@sof123 I am not sure this is the right revenue for this but I have trouble setting up Fiddler (https snooper) to work with Tinder. My theory is that it is somehow working out that there is snooper? I am getting SSL Certificate Failed or similar error to do with incorrect date time.  Can you give me possibly give me a quick run down? Appreciate it.

**Comment by sof123** [comment]
@ttse007 Did you download the certificate to your phone? Maybe Tinder's updated something to not allow it, but I followed these instructions to get it working: http://ec2-52-42-144-243.us-west-2.compute.amazonaws.com/tinder/

**Comment by zupd** [comment]
I also noticed this issue when I made a tinder autolike script. using .like(), but the likes_remaining is still 100 and not changing even if I try to like e.g. 200 users
