### ISSUE TITLE
ImportError: cannot import name _thread

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#116]
**What is the solution to this Error while importing pynder?**
**ImportError: cannot import name _thread**

```
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin

>>> import pynder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/__init__.py", line 1, in <module>
    from .session import Session  # NOQA
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 4, in <module>
    from . import models
  File "/Library/Python/2.7/site-packages/pynder/models/__init__.py", line 1, in <module>
    from .friend import Friend  # NOQA
  File "/Library/Python/2.7/site-packages/pynder/models/friend.py", line 2, in <module>
    from .user import User
  File "/Library/Python/2.7/site-packages/pynder/models/user.py", line 1, in <module>
    import dateutil.parser
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 43, in <module>
    from . import tz
  File "/Library/Python/2.7/site-packages/dateutil/tz/__init__.py", line 1, in <module>
    from .tz import *
  File "/Library/Python/2.7/site-packages/dateutil/tz/tz.py", line 23, in <module>
    from ._common import tzname_in_python2, _tzinfo, _total_seconds
  File "/Library/Python/2.7/site-packages/dateutil/tz/_common.py", line 2, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
```

What is the solution to this Error while importing pynder?

**Comment by charliewolf** [comment]
try updating dateutil and/or six
