### ISSUE TITLE
Issue in user model when doing recursion of nearby_users.

### ISSUE THREAD

**Issue by VeNoMouS** [charliewolf/pynder#152]
If trying to get a length of nearby_users() via `len(list(self.session.nearby_users()))` or `sum(1 for _ in self.session.nearby_users())` we are presented with the following error..

```
  File "/usr/local/lib/python2.7/dist-packages/pynder-0.0.13-py2.7.egg/pynder/session.py", line 30, in nearby_users
    yield Hopeful(user, self)
  File "/usr/local/lib/python2.7/dist-packages/pynder-0.0.13-py2.7.egg/pynder/models/user.py", line 27, in __init__
    self.schools_id.extend([school["id"] for school in data['schools']])
KeyError: 'id'
```

**Comment by VeNoMouS** [comment]
This can be resolved by adding a simple sanity check .. in *pynder/models/user.py*

```self.schools_id.extend([school["id"] for school in data['schools'] if hasattr(school, 'id')]```

**Comment by jakob400** [comment]
I did that, but now I'm getting the errors: 

```
Traceback (most recent call last):
  File "testapp.py", line 1, in <module>
    import pynder
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pynder/__init__.py", line 1, in <module>
    from pynder.session import Session  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pynder/session.py", line 6, in <module>
    from pynder.models import Profile, Hopeful, Match, Friend
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pynder/models/__init__.py", line 1, in <module>
    from pynder.models.friend import Friend  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pynder/models/friend.py", line 2, in <module>
    from pynder.models.user import User
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pynder/models/user.py", line 29
    self.jobs.extend(["%s @ %s" % (job["title"]["name"], job["company"]["name"]) for job in data['jobs'] if 'title' in job and 'company' in job])
       ^
SyntaxError: invalid syntax
```

**Comment by VeNoMouS** [comment]
sorry missing a `)`

**Comment by charliewolf** [comment]
fixed in master
