### ISSUE TITLE
Pynder Import Error (AttributeError: 'module' object has no attribute 'api')

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#164]
Pynder gives this Error

```>>> import pynder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/__init__.py", line 1, in <module>
    from pynder.session import Session  # NOQA
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 4, in <module>
    import pynder.api as api
AttributeError: 'module' object has no attribute 'api'
```

How to fix/resolve it?

Thank you!

**Comment by SHABINTHEGREAT** [comment]
And now this Error too:

```
>>> import pynder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/__init__.py", line 1, in <module>
    from .session import Session  # NOQA
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 5, in <module>
    from . import models
  File "/Library/Python/2.7/site-packages/pynder/models/__init__.py", line 1, in <module>
    from .me import Profile  # NOQA
  File "/Library/Python/2.7/site-packages/pynder/models/me.py", line 1, in <module>
    import dateutil.parser
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 43, in <module>
    from . import tz
  File "/Library/Python/2.7/site-packages/dateutil/tz/__init__.py", line 1, in <module>
    from .tz import *
  File "/Library/Python/2.7/site-packages/dateutil/tz/tz.py", line 23, in <module>
    from ._common import tzname_in_python2, _tzinfo, _total_seconds
  File "/Library/Python/2.7/site-packages/dateutil/tz/_common.py", line 2, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
```

How to fix/resolve them all and make Pynder functional?
Thank you!
