### ISSUE TITLE
Can't authenticate since last update (tinder web)

### ISSUE THREAD

**Issue by enric1994** [charliewolf/pynder#186]
Since the last Sunday I can't connect with tinder:

```
Traceback (most recent call last):
  File "C:/Users/enric/Documents/myProjects/tinderquiz/tinderQuiz.py", line 21, in <module>
    session = pynder.Session(facebook_id=fbID, facebook_token=token)
  File "C:\Users\enric\AppData\Roaming\Python\Python27\site-packages\pynder\session.py", line 18, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "C:\Users\enric\AppData\Roaming\Python\Python27\site-packages\pynder\api.py", line 25, in auth
    raise errors.RequestError("Couldn't authenticate")
pynder.errors.RequestError: Couldn't authenticate
```

Thanks

**Comment by Templada** [comment]
same here...
