### ISSUE TITLE
404 error when calling session.matches()

### ISSUE THREAD

**Issue by sof123** [charliewolf/pynder#188]
Did the API change? Here's the stack trace:

Traceback (most recent call last):
  File "tinder.py", line 132, in <module>
    run_stalker(email, password)
  File "tinder.py", line 87, in run_stalker
    match_list = list(session.matches())
  File "C:\Users\Joe_\Anaconda3\lib\site-packages\pynder\session.py", line 42, in <genexpr>
    return (Match(match, self) for match in response if 'person' in match)
  File "C:\Users\Joe_\Anaconda3\lib\site-packages\pynder\models\user.py", line 133, in __init__
    match['person']['_id'])['results']
  File "C:\Users\Joe_\Anaconda3\lib\site-packages\pynder\api.py", line 90, in user_info
    return self._get("/user/" + user_id)
  File "C:\Users\Joe_\Anaconda3\lib\site-packages\pynder\api.py", line 48, in _get
    return self._request("get", url)
  File "C:\Users\Joe_\Anaconda3\lib\site-packages\pynder\api.py", line 42, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 404

**Comment by sof123** [comment]
Looked into it and realized it was just a problematic match, some "Ms. Claus" match that was created by Tinder. Maybe the pynder devs should look into catching 404 errors while generating the list of matches.

**Comment by flipdazed** [comment]
This is because users have deleted Tinder. Modify the class `Match` like this e.g.

```
        if 'person' in match:
            try:
                _id = match['person']['_id']
                user_data = _session._api.user_info(_id)['results']
                user_data['_id'] = _id
                self.user = User(user_data, _session)
                self.messages = [
                    Message(m, user=self.user)
                    for m in match['messages']
                ]
            except Exception as e:
                print 'User Deleted: {}'.format(self.id)
```

**Comment by sof123** [comment]
@flipdazed Thanks, but it actually wasn't. It was because there was a problematic "Ms. Claus" profile that for some reason gave a 404 when you try to get its info. The issue was only with one profile. 

I am aware that Tinder is now (very recent change) giving 404s for users that have deleted the app, but I raised this issue over a month ago so that has nothing to do with this. 

Edit: Looks like Tinder is no longer giving 404s for users who have deleted their profiles. Don't know what that change was about but everything seems to be back to normal.
