### ISSUE TITLE
ERROR: Failure: ImportError (No module named cached_property)

### ISSUE THREAD

**Issue by safciplak** [charliewolf/pynder#197]
i have get some errors please help me. i want to execute this code.

➜  pynder git:(master) ✗ nosetests pynder --with-coverage --cover-package pynder

E
======================================================================
ERROR: Failure: ImportError (No module named cached_property)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/numpy/1.14.3_1/libexec/nose/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/Cellar/numpy/1.14.3_1/libexec/nose/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/Cellar/numpy/1.14.3_1/libexec/nose/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/anonymous/Desktop/pynder/pynder/__init__.py", line 1, in <module>
    from pynder.session import Session  # NOQA
  File "/Users/anonymous/Desktop/pynder/pynder/session.py", line 2, in <module>
    from cached_property import cached_property
ImportError: No module named cached_property

Name                           Stmts   Miss  Cover
--------------------------------------------------
pynder/__init__.py                 1      0   100%
pynder/api.py                     98     98     0%
pynder/constants.py               16     16     0%
pynder/errors.py                  10     10     0%
pynder/models/__init__.py          5      5     0%
pynder/models/base.py              2      2     0%
pynder/models/friend.py           25     25     0%
pynder/models/me.py               69     69     0%
pynder/models/message.py          35     35     0%
pynder/models/user.py             99     99     0%
pynder/session.py                 49     47     4%
pynder/tests/__init__.py           0      0   100%
pynder/tests/test_session.py      17     17     0%
pynder/tests/utils.py             15     15     0%
--------------------------------------------------
TOTAL                            441    438     1%
----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by kelvinheng92** [comment]
pip install cached-property
