### ISSUE TITLE
KeyError: 'id' for User object __init__

### ISSUE THREAD

**Issue by broaddaysk** [charliewolf/pynder#201]
I'm getting a KeyError for 'id' when trying to create User objects:

```python
Traceback (most recent call last):
  File "bot.py", line 76, in <module>
    for x in session.matches():
  File "/usr/local/lib/python3.5/dist-packages/pynder/session.py", line 42, in <genexpr>
    return (Match(match, self) for match in response if 'person' in match)
  File "/usr/local/lib/python3.5/dist-packages/pynder/models/user.py", line 135, in __init__
    self.user = User(user_data, _session)
  File "/usr/local/lib/python3.5/dist-packages/pynder/models/user.py", line 27, in __init__
    self.schools_id.extend([school["id"] for school in data['schools']])
  File "/usr/local/lib/python3.5/dist-packages/pynder/models/user.py", line 27, in <listcomp>
    self.schools_id.extend([school["id"] for school in data['schools']])
KeyError: 'id'
```

**Comment by stefansal** [comment]
I'm getting the same error! I have quickly fixed it by adding the following code to pynder/model/users.py on line 36/37.
Maybe this can be incorporated into the library?
```
        except KeyError:
            pass
```

**Comment by SolbiatiAlessandro** [comment]
I am getting the same keyerror, I agree with @stefansal above, should add KeyError

**Comment by taseppa** [comment]
Did you guys install pynder using pip? The pip version seems to be really old and caused the exact same problem for me.

**Comment by SolbiatiAlessandro** [comment]
yes, just did pip install pynder. Do you think there is a newer version available?

**Comment by broaddaysk** [comment]
Just for reference, I got the same error while using Python 3. Also, I just checked the pull request history and it looks like a patch for this issue was proposed in 2017 but never accepted, which leads me to believe that pynder is not currently maintained

**Comment by cjekel** [comment]
> yes, just did pip install pynder. Do you think there is a newer version available?

As taseppa pointed out, the version on PyPI is very old. You should clone this repo and install pynder from source.
```
git clone https://github.com/charliewolf/pynder
pip install ./pynder
```
