### ISSUE TITLE
Unable to get Tinder auth token 

### ISSUE THREAD

**Issue by ptamas88** [charliewolf/pynder#216]
I managed to get my FB token, and my FB id, but unable to get a tinder X-auth-token for further requests
I tried` https://api.gotinder.com/auth` endpoint with `{'facebook_token':'xxx', 'facebook_id': 'xxx'}` json

With this endpoint i got response 200 with the response contains only the 'OK' text.

Next step: I tried `https://api.gotinder.com/v2/auth/login/facebook` endpoint with only `facebook_token` in the json. In this case I got error 401 every time.

I do these steps because I expect a json response with `auth_token` tag or something similar in it which is the session X_auth_token.

How to get the X_auth_token nowadays?

**Comment by ismu** [comment]
Use this script to get XAuthToken [https://github.com/fbessez/Tinder/blob/master/phone_auth_token.py](url)

**Comment by dhrumin75** [comment]
> Use this script to get XAuthToken [https://github.com/fbessez/Tinder/blob/master/phone_auth_token.py](url)

@ismu I got the XAuthToken and tried running the following code:
`session = pynder.Session(XAuthToken='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')
print(session.profile)`

..and got the following error:
`Traceback (most recent call last):
  File "C:/Users/Dhrumin/PycharmProjects/tinderproj/demo.py", line 43, in <module>
    print(session.profile)
  File "C:\Users\Dhrumin\AppData\Roaming\Python\Python36\site-packages\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\Dhrumin\AppData\Roaming\Python\Python36\site-packages\pynder\session.py", line 22, in profile
    return Profile(self._api.profile(), self._api)
  File "C:\Users\Dhrumin\AppData\Roaming\Python\Python36\site-packages\pynder\api.py", line 68, in profile
    return self._get("/profile")
  File "C:\Users\Dhrumin\AppData\Roaming\Python\Python36\site-packages\pynder\api.py", line 47, in _get
    return self._request("get", url)
  File "C:\Users\Dhrumin\AppData\Roaming\Python\Python36\site-packages\pynder\api.py", line 41, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 400`

I have already installed the latest pynder. I also tried it with FB token (198 characters long token) and FB id but I think the authentication is failing and it throws JSONDecodeError mentioned in this issue: [https://github.com/charliewolf/pynder/issues/208](url)

**Comment by kotaroyama** [comment]
Hey, I've just written [a python script](https://github.com/kotaroyama/Get-Tinder-XAuthToken) to retrieve a XAuthToken just using your Facebook email and password.

**Comment by RMatushkin** [comment]
Who wants to sniff Tinder API of the latest official app (v3 api version), you can write to me and I'll explain how to do it.
