### ISSUE TITLE
RequestError: 400 even though it passes all three tests fine

### ISSUE THREAD

**Issue by aferrei3** [charliewolf/pynder#217]
I keep getting request errors even though when i run nosetests pynder --with-coverage --cover-package pynder it passes all three tests.

Here's my code
import pynder
session = pynder.Session(facebook_id, facebook_auth_token) #kwargs
session.matches() # get users you have already been matched with

Here's my Error
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "C:\Users\andre\Documents\pynder-master\pynder-master\pynder\session.py", line 47, in matches
    response = self._api.matches(since)
  File "C:\Users\andre\Documents\pynder-master\pynder-master\pynder\api.py", line 84, in matches
    return self.updates(since)['matches']
  File "C:\Users\andre\Documents\pynder-master\pynder-master\pynder\api.py", line 61, in updates
    return self._post("/updates", {"last_activity_date": since} if since else {})
  File "C:\Users\andre\Documents\pynder-master\pynder-master\pynder\api.py", line 55, in _post
    return self._request("post", url, data=data)
  File "C:\Users\andre\Documents\pynder-master\pynder-master\pynder\api.py", line 46, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 400

**Comment by cjekel** [comment]
Is vcrpy not sending new requests?

Change ```record_mode="once"``` to ```record_mode="all"``` to force vcrpy to make new requests.
