### ISSUE TITLE
pynder.errors.RequestError: 500

### ISSUE THREAD

**Issue by holdenjrussell** [charliewolf/pynder#218]
Hi. Trying to use. Looks like the api is having issues when trying to update location filter.
here is the traceback
Hello  Holden
Traceback (most recent call last):
  File "/usr/local/bin/tindetheus", line 10, in <module>
    sys.exit(command_line_run())
  File "/usr/local/lib/python3.6/dist-packages/tindetheus/tindetheus.py", line 274, in command_line_run
    main(args, defaults['facebook_token'], defaults['XAuthToken'])
  File "/usr/local/lib/python3.6/dist-packages/tindetheus/tindetheus.py", line 62, in main
    likes_left=args.likes, x_auth_token=x_auth_token)
  File "/usr/local/lib/python3.6/dist-packages/tindetheus/tinder_client.py", line 95, in __init__
    self.session.profile.distance_filter = self.search_distance
  File "/usr/local/lib/python3.6/dist-packages/pynder/models/me.py", line 32, in __set__
    instance.__init__(instance._api.update_profile(profile), instance._api)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 98, in update_profile
    return self._post("/profile", profile)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 63, in _post
    return self._request("post", url, data=data)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 54, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 500

**Comment by holdenjrussell** [comment]
i'm using xAuthToken
