### ISSUE TITLE
KeyError company on user.py line 23

### ISSUE THREAD

**Issue by vyscond** [charliewolf/pynder#39]
I got this exception today

```
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    users = session.nearby_users()
  File "/Users/vyscond/Documents/tynder/env/lib/python2.7/site-packages/pynder/session.py", line 20, in nearby_users
    return [models.Hopeful(u, self) for u in users]
  File "/Users/vyscond/Documents/tynder/env/lib/python2.7/site-packages/pynder/models/user.py", line 23, in __init__
    self.jobs.extend(["%s @ %s" % (job["company"]["name"], job["title"]["name"]) for job in data['jobs'] if 'title' in job])
KeyError: 'company'
```

I think it's good to append the __KeyError__ exception to the current code

```python
        try:
            self.schools.extend([school["name"] for school in data['schools']])
            self.jobs.extend(["%s @ %s" % (job["company"]["name"], job["title"]["name"]) for job in data['jobs'] if 'title' in job])
            self.jobs.extend(["%s" % (job["company"]["name"],) for job in data['jobs'] if 'title' not in job])
        except ValueError:
            pass
        except KeyError: # handling missing company
            pass
```

**Comment by charliewolf** [comment]
Can you open a PR with this?

**Comment by vyscond** [comment]
I think i can In a few hours.
