### ISSUE TITLE
matches[].delete() – Error

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#63]
**Matches[].delete() – Error**
CODE:

**`matches[1111].delete()`**
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/Library/Python/2.7/site-packages/pynder/models/user.py", line 136, in delete
    return self._session._api._request('DELETE', '/user/matches/' + self.id)`
`  File "/Library/Python/2.7/site-packages/pynder/api.py", line 43, in _request
    raise errors.RequestError(result.status_code)`
`pynder.errors.RequestError: 400`

Most matches can be deleted, and returns code 200. Deleting some matches give the above error and code 400. What is causing them only for some matches?

**Comment by SHABINTHEGREAT** [comment]
This is not a problem with Pynder, it seems.
It seems that there are some ghost users in the match list without the **user** attribute. Hence, they cannot be deleted, apparently.
