### ISSUE TITLE
Location update error

### ISSUE THREAD

**Issue by Nateliason** [charliewolf/pynder#7]
I'm getting this error when I try to update my location:

```
Traceback (most recent call last):
  File "pynderTest.py", line 8, in <module>
    print session.update_location(45, 93)
  File "build/bdist.macosx-10.6-intel/egg/pynder/session.py", line 18, in update_location
  File "build/bdist.macosx-10.6-intel/egg/pynder/api.py", line 78, in ping
  File "build/bdist.macosx-10.6-intel/egg/pynder/api.py", line 43, in _post
pynder.errors.RequestError: 200
```

Here's my code:

```
import pynder

FBTOKEN = ""
FBID = ""

session = pynder.Session(FBID, FBTOKEN)

print session.update_location(45.098, 93.143)
```

**Comment by charliewolf** [comment]
@Nateliason can you update to the latest master and try this again?

**Comment by Nateliason** [comment]
Now it prints out 

```
{u'status': 200}
```

Is that a success message? Hard to tell.

**Comment by charliewolf** [comment]
Yes, that means it was successful.

**Comment by charliewolf** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success

**Comment by charliewolf** [comment]
Updated in version 0.0.4 & pushed to PyPi

**Comment by Nateliason** [comment]
Sweet, thanks!
