### ISSUE TITLE
<class 'pynder.errors.RequestError'> 504

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#78]
**`<class 'pynder.errors.RequestError'> 504`**

On calling **`session.matches()`**

This did not happen until a week ago.

**Comment by SHABINTHEGREAT** [comment]
**`>>> mx = session.matches()`**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 33, in matches
    return [models.Match(m, self) for m in self._api.matches()]
  File "/Library/Python/2.7/site-packages/pynder/models/user.py", line 133, in __init__
    match['person']['_id'])['results']
  File "/Library/Python/2.7/site-packages/pynder/api.py", line 94, in user_info
    return self._get("/user/" + user_id)
  File "/Library/Python/2.7/site-packages/pynder/api.py", line 48, in _get
    return self._request("get", url)
  File "/Library/Python/2.7/site-packages/pynder/api.py", line 44, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 504
```

**Comment by modulebaan** [comment]
HTTP Error 504 Gateway timeout
I also have received those errors a couple months ago. The Tinder servers aren't responding to the requests from Pynder.

**Comment by charliewolf** [comment]
Tinder is doing some sort of blocking

**Comment by SHABINTHEGREAT** [comment]
It **works** now!
It seems that this is a recurring problem – from _modulebaan_'s statement.
