### ISSUE TITLE
Unable to authenticate with facebook auth token.

### ISSUE THREAD

**Issue by kngu9** [charliewolf/pynder#93]
Hello,
I'm unable to authenticate my account, it keeps saying that the error is 401.

Is there a correct way of obtaining the facebook id and auth token?

**Comment by taneta** [comment]
For me this way worked  https://gist.github.com/rtt/10403467#gistcomment-1846343 
But you have to renew token every couple hours :(

**Comment by unreal99** [comment]
I am getting this error :tinder_social_examples.py
Traceback (most recent call last):
  File "C:\pynder\pynder-master\examples\tinder_social_examples.py", line 6, in <module>
    session = pynder.Session(FBID, FBTOKEN)
  File "C:\Users\x\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pynder-0.0.11-py3.5.egg\pynder\session.py", line 14, in __init__
    self.profile = models.Profile(self._api.profile(), self._api)
  File "C:\Users\x\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pynder-0.0.11-py3.5.egg\pynder\api.py", line 67, in profile
    return self._get("/profile")
  File "C:\Users\x\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pynder-0.0.11-py3.5.egg\pynder\api.py", line 46, in _get
    return self._request("get", url)
  File "C:\Users\x\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pynder-0.0.11-py3.5.egg\pynder\api.py", line 42, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 401

**Comment by halalfood** [comment]
I got the same error. I rolled back my pynder to an earlier version and it worked.

**Comment by baturalpgurdin** [comment]
@halalfood  which version did you use ?

**Comment by tobwen** [comment]
Same problem here. Version 0.0.11 from pip works.

**Comment by jlmartyres** [comment]
the guys who are getting an error

session = pynder.Session(FBID, FBTOKEN) no longer requires the ID, it will fail if you include it

only use Session(FBTOKEN)

**Comment by VeNoMouS** [comment]
just fyi, ```session = pynder.Session(FBID, FBTOKEN)```... this was changed sometime ago, session only requires token, not the id..

**Comment by halalfood** [comment]
@baturalpgurdin 0.0.11 from pip works >> newer version doesnt work
